version: "3.8"
services:
  # 1. Database service
  jobportal-db:
    container_name: mysqldb
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "timviec"
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - jobportal-network

  # 2. Backend service
  jobportal-backend:
    container_name: backend-container
    build:
      context: ./jobportal
      dockerfile: Dockerfile
    depends_on:
      - jobportal-db
    restart: always
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://jobportal-db:3306/timviec?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    networks:
      - jobportal-network

  # 3. Frontend service
  jobportal-frontend:
    container_name: frontend-container
    build:
      context: ./react-social
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - jobportal-backend
    networks:
      - jobportal-network

  # 4. NGINX service
  nginx:
    container_name: nginx-container
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
      - ./nginx/certs:/etc/nginx/certs:ro 
    depends_on:
      - jobportal-frontend
      - jobportal-backend
    networks:
      - jobportal-network

volumes:
  mysql_data:

networks:
  jobportal-network:
    driver: bridge