events { 
    worker_connections 1024; 
}

http {

    # 1. Khối server định tuyến cho Frontend (React)
    server {
        listen 443 ssl;
        server_name web.chausu.name.vn chausu.name.vn; # Nhận diện cả subdomain web và domain gốc
        ssl_certificate /etc/nginx/certs/chausu.crt;
        ssl_certificate_key /etc/nginx/certs/chausu.key;

        location / {
            proxy_pass http://jobportal-frontend:80; 
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    # 2. Khối server định tuyến cho Backend API (Spring Boot)
    server {
        listen 443 ssl;
        server_name api.chausu.name.vn; # Nhận diện subdomain api

         ssl_certificate /etc/nginx/certs/chausu.crt;
        ssl_certificate_key /etc/nginx/certs/chausu.key;
        location / {
            proxy_pass http://jobportal-backend:8080; 
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}