name: Deploy web app

on:
  push:
    branches: 
      - main
  pull_request: 
    branches:
      - main

jobs:
  # ==========================================
  # STAGE 1: CI - BUILD & PUSH DOCKER IMAGES
  # =========================================
  Build-and-Push:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      # 1/ Backend Image
      - name: Build And Push Backend Image (Java Spring Boot)
        uses: docker/build-push-action@v5
        with:
          context: ./jobportal
          file: ./jobportal/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/jobportal-backend:latest

      # 2/ Frontend Image
      - name: Build And Push Frontend Image (Reactjs)
        uses: docker/build-push-action@v5
        with:
          context: ./react-social
          file: ./react-social/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/jobportal-frontend:latest

  # ==========================================
  # STAGE 2: CD - DEPLOY TO SERVER
  # ==========================================
  Deploy-on-server:
    runs-on: ubuntu-latest
    needs: Build-and-Push # Only deploy when stage 1 is successfull
    if: github.event_name == 'push' # Only deploy when code is merged or in the main branch

    steps:
      - name: SSH and run deploy script
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 24700
          script: |
            cd /root/chausu-compose-web/Deploy-web-ssearching-job-portal
            echo "Pulling the latest images from Docker Hub....."
            docker compose pull

            echo "Restarting containers..."
            docker compose up -d

            echo "Cleaning unused images..."
            docker image prune -f

            echo "Check containers..."
            docker compose ps

            echo "Deployment completed."
            
      
      
