name: Deploy web app

on:
  push:
    branches: 
      - main

jobs:
  Deploy-for-chausu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-code-for-ChauSu
        uses: actions/checkout@v4

      - name: SSH and run deploy script
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 24700
          script: |
            cd /root/chausu-compose-web/Deploy-web-ssearching-job-portal
            echo "Pull latest source..."
            git pull origin main

            echo "Build and restart containers..."
            docker compose down
            docker compose up -d --build

            echo "Check containers..."
            docker compose ps

            echo "Check logs..."
            docker compose logs --tail=50

            echo "Verify website..."
            curl -I https://web.chausu.name.vn

            echo "Verify API..."
            curl -k https://api.chausu.name.vn

            echo "Deployment completed."
            
      
      
