name: Deploy web app

on:
  push:
    branches: 
      - main

jobs:
  Deploy-for-chausu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-code-for-ChauSu
        uses: actions/checkout@v4

      - name: SSH and run deploy script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 24700
          script: |
            cd /root/chausu-compose-web/Deploy-web-ssearching-job-portal
            ./deploy.sh
      
      
